# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data

```{r Loading and preprocessing data}
data <- read.csv("activity.csv")
data_filtered <- data[!is.na(data$steps),]
data_split <- with(data_filtered, split(steps, date))
steps_by_day <- lapply(data_split, sum)
steps_by_day <- unlist(steps_by_day)
```

## Mean total number of steps taken per day

```{r Mean total number of steps taken per day, echo=FALSE}
hist(steps_by_day, main = "Histogram of steps per day", xlab = "Steps per day")
cat("Mean steps per day: ", mean(steps_by_day))
cat("Median steps per day: ", median(steps_by_day))
```

## Average daily activity pattern

```{r Average daily activity pattern, echo=FALSE}
data_split <- with(data_filtered, split(steps, interval))
steps_by_interval <- lapply(data_split, mean)
x_axis <- names(steps_by_interval)
plot(x_axis, steps_by_interval, type = "l", xlab = "Interval", ylab = "Steps", main = "Time series: interval vs steps")
maxim <- max(as.numeric(steps_by_interval))
maxim_interval <- names(steps_by_interval[steps_by_interval == maxim])
cat("Interval with average maximum steps, average maximum steps = ", maxim_interval,",", maxim)
```

## Inputing missing values (NAs replaced with mean of steps across intervals)

```{r Count of missing values, echo=FALSE}
miss_values <- sum(is.na(data$steps))
cat ("Number of missing values: ", miss_values)
```

```{r Input missing values}
# replacing missing values with mean of steps across respective interval
temp <- with(data_filtered, split(steps, interval))
temp <- lapply(temp, mean)
temp <- data.frame(interval = names(temp),  steps = unlist(temp))
data[is.na(data)] <- ceiling(temp$steps)
```

``` {r Histogram with NAs replaced, echo=FALSE}
data_split <- with(data, split(steps, date))
steps_by_day <- lapply(data_split, sum)
steps_by_day <- unlist(steps_by_day)
hist(steps_by_day, main = "Histogram of steps per day (after replacing NAs)", xlab = "Steps per day")
cat("Mean steps per day (after replacing NAs): ", mean(steps_by_day))
cat("Median steps per day (after replacing NAs): ", median(steps_by_day))
cat("Observation in mean/ median: mean has shifted, median has not.")
```

## Differences in activity patterns between weekdays and weekends
```{r Activity pattern between weekdays and weekends, echo=FALSE}
temp_dates <- as.Date(data$date)
temp_dates <- weekdays(temp_dates)
temp_dates <- as.factor(ifelse(temp_dates %in% c("Saturday", "Sunday"), "Weekend", "Weekday"))
data_temp <- data
data_temp$weekdays <- as.factor(temp_dates)
data_split <- with(data_temp, split(steps, interval))
steps_by_interval <- lapply(data_split, mean)
data_temp$mean <- unlist(steps_by_interval)
library(lattice)
xyplot(mean ~ interval | weekdays, data = data_temp, layout = c(1,2), type = "l", xlab = "Interval", ylab = "Number of Steps")
```
